db:
  num: 1
  user: zytcft
  password: Zaq12wsx
  url:
    0: jdbc:mysql://192.168.1.221:3306/kernel_config?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true